# -*- coding: utf-8 -*-
"""Area of circle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V3O_AoiFPWFkjl10Yoj_rIwXXkVt8P2i

Area of circle
"""

radius = float(input("enter the radius:"))
pi= 3.14
area=pi * radius * radius
print("the area of circle is :",area)