stName=input("enter the name of the student:")
stUSN =input("enter the usn of the student:")
stmarks1=int(input("enter the marks of sublect1:"))
stmarks2=int(input("enter the marks of subject2:"))
stmarks=int(input("enter the marks of sublect3:"))

print("student details""============================================================")
print("%12s"% "NAME:",stName)
print('%12s'% "USN :",stUSN)
print("%12s"% "marks1:",stmarks1)
print("%12s"% "marks2:",stmarks2)
print("%12s"% "marks3:",stmarks)
print("%12s"% "total:",stmarks+stmarks1+stmarks2)
print("%12s"% "percent:",((stmarks+stmarks1+stmarks2)/3))
print("=====================================================")
